### PR TITLE
updated dependencies, fixed caching and status

### LINKED ISSUE #125: !hangman seems to ignore guesses after ~2m
As title, the hangman command seems to ignore any guesses after ~2 minutes - a minute less than the 3m it says people have. It waits the full 3m to post the answer but for a period of time it just doesn't accept new guessed letters.

When you fix this, may I suggest that you also show the time remaining (at least at every 30 second intervals if not an actual count down).

### PR DESCRIPTION
**Pull request by bra1n**
this fixes #125 and #126

### CODE REVIEW

**Comment by multimeric** [comment]
If you bumped discord.js, did you check that the message embeddings still work? Because when I did that, the description couldn't be markdown anymore.

**Comment by bra1n** [comment]
Both !hangman and !card still seem fine to me:
image
image
Is there something in particular that you saw break with the update?

**Comment by multimeric** [comment]
Hmm, none of that worked when I bumped discord.js. The code blocks printed out literal backticks, and the italics had literal asterisks etc

**Comment by bra1n** [comment]
> Hmm, none of that worked when I bumped discord.js. The code blocks printed out literal backticks, and the italics had literal asterisks etc

Hm, maybe because you're using `12.1.1` and I'm using `12.2.0`?

**Comment by multimeric** [comment]
Good point, I'll check that

**Comment by bra1n** [comment]
I just deployed it online and it also looks like it's working there.

**Pull request merged**
