### PR TITLE
Slash typescript

### PR DESCRIPTION
**Pull request by multimeric**
## Changes

* Port to typescript, including some newer JS features such as:
    * More `async`/`await`, less `.then()`
    * More `import`, less `require()`
* Use [`discord-ts`](https://github.com/oceanroleplay/discord.ts) decorators
* Port all commands to using slash commands
* Bump many packages
* Replace `requests` with `node-fetch`
* Use [scryfall-ts](https://github.com/ChiriVulpes/scryfall-sdk) for Scryfall requests, which gives us:
    * Good type definitions
    * A nice TS API that lets us easily add query parameters, and have them type checked
* For `/standard`, update the [`whatsinstandard`](https://github.com/glacials/whatsinstandard) API to v6

## TODO
* [ ] Re-implement some cut features like the spam filtering, and the help command
* [x] Test all commands more thoroughly
* [x] Add more comprehensive TS type annotations, at least to all functions
* [ ] Fix tests
* [x] Run prettier

### CODE REVIEW

**Comment by multimeric** [comment]
I think I need a specific set of *minimal* requirements before you will merge here, because I'm still of the opinion that this is good to go as a starting point.

**Comment by bra1n** [comment]
> I think I need a specific set of _minimal_ requirements before you will merge here, because I'm still of the opinion that this is good to go as a starting point.

From what I've seen, the changes look good so far! I guess there are only 3 things I'd consider mandatory before releasing the bot:
- fix merge conflicts
- check if the bot permissions are still appropriate to what it is doing with slash commands now. if not, I'll have to update the link in the project description
- add some kind of (temporary) help to migrate the users from !commands to /commands. For example, a tiny module that listens for !card and outputs a "Judgebot is using /slash commands now, please use /card". if this proves to hard / time consuming, the user status should at least give some hint to the new command syntax

**Comment by multimeric** [comment]
The first two are easy. Listening for messages I think is an issue because it will force the bot to use the gateway at all, which I *think* (not certain) is what causes the disconnects, because Discord boots the bot off the gateway. So I'd rather go with the status option there.

**Comment by bra1n** [comment]
Ah yeah, that makes sense. How about a small change to the old code that shows a warning that the bot will switch to /slash commands in the near future, and then deploy the new version in a week or so?

**Comment by multimeric** [comment]
Sure, I'd be happy to do that. I can write a PR for that in a few days.

**Comment by multimeric** [comment]
Hmm I wanted to use the status but there's not really enough space to convey any message. What kind of warning do you suggest?

image

**Comment by bra1n** [comment]
Hm yeah, fair point. Maybe just "Listening to /slash commands [or just 'cmds'] now"? We can put some extra text in the "about me" box like this: 
image

**Comment by multimeric** [comment]
Yep that's doable, but I think you have to edit the bio because it will be in the app dashboard.

**Comment by multimeric** [comment]
Also my feeling is that "slash command" isn't a term that most users will be familiar with. So I'm wondering if there's a way to write it in a way users will understand. My current approach is:
image

(that's the Soon emoji)

**Comment by bra1n** [comment]
As mentioned earlier, I'd add a separate info message to the current !card command to prepare people for the release, which should hopefully give enough warning before we release the new version. So what you suggested should be fine.

**Pull request merged**
