### PR TITLE
Initial slash command work

### PR DESCRIPTION
**Pull request by multimeric**
## Changes:

* Created a new `getInteractions()` method for the module classes, which returns a list of interactions (ie slash commands) it can handle, how to handle them, and a description of them for the discord API
* Implement `getInteractions` for the card module, and handle the interactions using the same command handling logic we used for message commands
* Move most of the command handling logic for the card class into `handleCommand`. `handleMessage` is then a specific method for handling message commands only (as opposed to interaction commands)
* Listen for interactions in the bot, and hook that up to the above `getInteractions()` method
* Refactor some common stuff into `utils.js`
* Add a utility script that can be invoked using `npm run update-interactions`, which `PUT`s the interaction documentation up to the discord API. This is what provides the slash command documentation for users
* Bump a few package versions

## Remaining Work

Since I don't have the API token, it's very difficult for me to actually test this. I can't test that the interactions are pushing correctly, or even start a test server easily. It would be great if someone with permissions to do this (ie @bra1n) could have a play around. Feel free to ping me if there are serious issues, but I'm hoping it should be easy enough to finish from here with only a small amount of code.

## Future Steps

* This only covers the "card" command. The hangman, help, and rules modules are not yet implemented.
* Deprecate the text commands entirely - I feel that slash commands are a better way to provide interactivity
* Respond to users using replies

## Linked Issues

#146

### CODE REVIEW

**Comment by bra1n** [comment]
Hey Michael,
it looks like you've clearly put in time and effort to improve the judgebot, a project that I haven't touched in ages and which I have neither the time (nor the interest) to keep maintaining right now. Magic in general is something that I haven't spent any time with for a long while now and it would be quite sad if this were the end of a bot that is currently in use on about 4200 servers.
So here's an idea: how about I make you a collaborator on the project and you can make any changes you want yourself, while I (for now) stay in the background, continue hosting the bot and help you out if you run into any problems? I could do the occasional PR code review, too, probably. 😅 

About testing your own changes: it is quite simple to set up your own bot on Discord and use that for hosting a local copy of judgebot. Just head over to https://discord.com/developers/applications , create a new "Application" and then use the private token to get your local bot up and running in order to add it to a test server. Let me know if you need further help with that!

**Comment by multimeric** [comment]
Hi Steffen. Thanks for the offer, I'm happy to accept. I agree with your reasoning which is why I wanted to put in a PR here instead of just running a fork of judgebot for my own server.

**Comment by bra1n** [comment]
Alright, I added you as a collaborator. Please ping me on Discord (bra1n#8125) when you have some time so that we can figure out how to go from here. 😃

**Comment by multimeric** [comment]
Closed in favour of #159.

**Pull request closed without merging**
